export const data = [
  {
    question: "What is the correct command to create a new React project?",
    option1: "npx create-react-app appname",
    option2: "npm install create-react-app",
    option3: "npx install create-react-app -g",
    option4: "install - l create-react-app",
    ans: 1,
  },
  {
    question: "Which of the following is true regarding Babel ?",
    option1: "Compiler",
    option2: "Transpilar",
    option3: "Both of the above",
    option4: "None of the above",
    ans: 3,
  },
  {
    question: "Which of the following best describes MongoDB?",
    option1: " Relational database",
    option2: "Spreadsheet program",
    option3: "Document-based NoSQL database",
    option4: "Graph database",
    ans: 3,
  },
  {
    question:
      "Which MongoDB command is used to display the database you are currently using?",
    option1: "show currentDatabase",
    option2: "show db",
    option3: "see db",
    option4: "db",
    ans: 2,
  },
  {
    question: "Node.js is written in",
    option1: "JavaScript",
    option2: "C",
    option3: "C++",
    option4: "All of the above",
    ans: 4,
  },
  {
    question: "What is the default scope in the Node.js application ?",
    option1: "Global",
    option2: "Local",
    option3: "Global Function",
    option4: "Local to object",
    ans: 2,
  },
];
